import ReduxProvider from '@/redux/ReduxProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import './globals.css';

import AuthGuard from '@/auth/AuthGuard';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Message App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ReduxProvider>
            <html lang="en">
                <body className={inter.className}>
                    <AuthGuard>
                        {children}
                        <ToastContainer
                            position="top-right"
                            autoClose={2000}
                            limit={3}
                            hideProgressBar={false}
                            newestOnTop={false}
                            closeOnClick
                            rtl={false}
                            pauseOnFocusLoss
                            draggable
                            pauseOnHover
                            theme="light"
                        />
                    </AuthGuard>
                </body>
            </html>
        </ReduxProvider>
    );
}
